### PR TITLE
Quick Cleaned Version of tasks/candidate-availability Branch

### PR DESCRIPTION
**Pull request by yehee**

### CODE REVIEW

**Review by smilosev — APPROVED** [review]
One bug: Should not be able to remove the first availability. We should do a check and not delete the availability if there is only one.

I have approved this and we will create a bug fixes branch and merge to master during our testing phase.

**Comment by bhenaghan** [comment]
Is this closed on purpose?

**Comment by yehee** [comment]
Yup, `feat/ca` branch was merged to `tasks/input-validation`, which was merged to `master` yesterday. Please test `master` branch and leave comments if you see any functionality missing there. Sorry for the confusion 😞.

**Comment by bhenaghan** [comment]
I don't know if it was a great idea to squash the commit into master, we've now got a single commit called `Implementing Input Validation` that has over a thousand changes in it and all the git blame/commit messages are now lost.

**Comment by yehee** [comment]
I believe your branch shouldn't be affected by this. It was just my branch and I didn't have anything to keep. Let me know if you have any questions!

**Pull request closed without merging**
