### PR TITLE
Add new user

### PR DESCRIPTION
**Pull request by dustxd**
Screen Shot 2019-10-28 at 3 59 47 PM
Screen Shot 2019-10-28 at 4 00 20 PM

### CODE REVIEW

**Comment by dustxd** [comment]
This PR addresses #20 and #21

**Comment by smilosev** [comment]
Looks awesome!! can you just add another field Phone after email because the backend expects this format

**Comment by smilosev** [comment]
Delete part opens up the dialog but button is weird.. Can you take a look ?

**Comment by dustxd** [comment]
> Delete part opens up the dialog but button is weird.. Can you take a look ?

Delete is not implemented yet, will be handling that in another issue.

**Pull request merged**
